baseURL = "https://kaitachi.github.io/"
languageCode = "en-us"
title = "Kaitachi's Blog"
theme = "hugo-theme-stack"


[params.style]
    darkestColor = "#242930" # Sidebar
    darkColor = "#353b43" # Main
    lightColor = "#afbac4" # Text
    lightestColor = "#ffffff" # Headers
    primaryColor = "hsl(24, 100%, 50%)" # Accent Color


#[menu]
#    [[menu.main]]
#        identifier = "home"
#        name = "Home"
#        url = "/"
#        weight = 1
#    [[menu.main]]
#        identifier = "tags"
#        name = "Tags"
#        url = "/tags/"
#        weight = 2
#    [[menu.main]]
#        identifier = "about"
#        name = "About"
#        url = "/about/"
#        weight = 3
